### ISSUE TITLE
Recording the wrong section

### ISSUE THREAD

**Issue by liviacarolgouvea** [pkp/quickSubmit#70]
**Description of the bug** 
When we click to start a quick submission, a new register is recorded in the publications table with the first section_id of the list order of sections. 
Even if we change the section, the section_id is not changed in the publications table.

**Implications**
When we click to save the submission, the flow reads the section_id in publications table to verify if an abstract is needed. So, even if we have chosen a section that doesn't need an abstract, the flow will verifies the requirements of the section recorded in the publications table and, if this section needs an abstract, it will stop the process.

**Expected behavior**
When starting a quick submission, no section_id should be saved in the publications table. After the user select the section, then the section_id of the correspondent section should be updated in the publications table.

**Comment by asmecher** [comment]
@liviacarolgouvea, what version of OJS and what version of the quick submit plugin are you using?

**Comment by liviacarolgouvea** [comment]
> @liviacarolgouvea, what version of OJS and what version of the quick submit plugin are you using?

 OJS 3.3.0.13
QuickSubmit Plugin 1.0.5 (but I also tested with QuickSubmit 1.0.6-1)

**Comment by bozana** [comment]
This is solved here: https://github.com/pkp/pkp-lib/issues/2644 and should be available in the next plugin release.
Thus, I will close the issue now...
