### ISSUE TITLE
quick_Submit showing installed but is not installed no install option

### ISSUE THREAD

**Issue by selhay** [pkp/quickSubmit#73]
quick_Submit showing installed but is not installed

quick_Submit is not listed in Webiste Settings/Plugins/Installed Plugins/Import/Export Plugins
But when I click on it in Plugin Gallery I get a message reading
"Plugin already installed, but can be updated to a newer version".
There's no option button to upgrade.

As a test I clicked on another plugin which I believe is not installed
and the popup message read "The plugin has not yet been installed."
but there is no install button in the popup.

The plugins/importexport dir does not have a quick_Submit
subdirectory.  

I have checked that shell_exec is enabled.

I did install quick_Submit and use it some time ago on the same
installation when it was 3.3.0-12. We upgraded to 3.3.0-15 but the
problem persists. 

Any ideas what has happened or how to fix it?
Thanks in advance.

**Comment by selhay** [comment]
image for original post 
![image](https://github.com/pkp/quickSubmit/assets/51990602/28bcde10-df38-43d8-a3e3-7dfb02cd3740)

**Comment by ctgraham** [comment]
@selhay , I see this question is also posted to the PKP community forum:
https://forum.pkp.sfu.ca/t/quick-submit-showing-installed-but-is-not-installed/80820

The forum is the better place to troubleshoot, so let's continue the conversation there.
