### ISSUE TITLE
Images In HTML Galleys Not Displaying When QuickSubmitted

### ISSUE THREAD

**Issue by cjwetherington** [pkp/quickSubmit#74]
Potentially related to #61, when using QuickSubmit to submit an HTML galley with a dependent image, the galley image is 404 when viewed in browser via the HTML Galley plugin.  Submitting the same galley without use of the QuickSubmit plugin, the embedded images are correctly rendered.

Using the "Change FIle" feature on the QuickSubmitted galley to re-upload the same galley and image files resolves the issue, but only if one chooses "This is not a revision of an existing file."  It would seem that perhaps the HTML Galley plugin is unable to correctly re-write the path of the embedded image when the galley/image files were submitted via QuickSubmit.

OJS: 3.3.0.13
QuickSubmit: v1.0.6.1 released 2023-02-03

**Comment by cjwetherington** [comment]
Here is a 3.5-minute video demonstrating the issue and workaround described:  https://psu.mediaspace.kaltura.com/media/quickSubmit/1_hn3l1nmj)

(Looks best when viewed in full-screen mode.  Note that the screen cap doesn't pick up some pop-up windows, e.g. for the file picker, so to clarify, the exact same HTML and image files were chosen each time.)

**Comment by asmecher** [comment]
@cjwetherington, [this change](https://github.com/pkp/quickSubmit/commit/15b5ea25355afb3dd8b5e4dd192d6fc4bbf2d626) should correct the issue for new submissions made via Quick Submit. For existing submissions that encountered this problem, you'll need to update some records in the database.

Make a backup before you do this!

1. Identify records that have the bad data:
   ```sql
   SELECT sf.submission_id, pg.publication_id, pg.galley_id FROM submission_files sf JOIN publication_galleys pg WHERE sf.file_stage=2 AND sf.submission_file_id = pg.submission_file_id;
   ```
   For example, this might give:
   ```
   +---------------+----------------+-----------+
   | submission_id | publication_id | galley_id |
   +---------------+----------------+-----------+
   |            24 |             25 |         5 |
   +---------------+----------------+-----------+
   1 row in set (0.001 sec)
   ```
   ...meaning we have one row to fix.
2. For each, find out what the `submission_file_id` *should* be (by `submission_id` value from the above query results):
   ```
   SELECT submission_file_id FROM submission_files WHERE submission_id=24 ORDER BY submission_file_id ASC LIMIT 1;
   ```
   This might give:
   ```
   +--------------------+
   | submission_file_id |
   +--------------------+
   |                 32 |
   +--------------------+
   1 row in set (0.000 sec)
   ```
3. Then, for each, replace the existing (incorrect) submission file ID with the correct value, this time using the galley ID from the first query results:
   ```
   UPDATE publication_galleys SET submission_file_id = 32 WHERE galley_id=5;
   ```

**Comment by asmecher** [comment]
@cjwetherington, if you can confirm that this resolves the issue for you, I'll get a new release of the plugin wrapped up!

**Comment by cjwetherington** [comment]
@asmecher, thanks very much indeed for the reply and fixes.  Both the patch and database methods are working perfectly for us.  Much appreciation.

**Comment by asmecher** [comment]
Great, glad to hear it!
