### ISSUE TITLE
Not working with OJS 3.4.0.3

### ISSUE THREAD

**Issue by felixhelix** [pkp/quickSubmit#75]
When trying to install the plugin via the gallery, i get the error message

`Cannot instantiate class. Class "ClassTypeDescription" is not declared in "lib.pkp.classes.filter.ClassTypeDescription"`
I tried it by cloning the plugin into my local OJS installation.
There the following error occured:
`PHP Fatal error:  Uncaught Error: Class "TemplateManager" not found in .../ojs/plugins/importexport/quickSubmit/QuickSubmitPlugin.inc.php:53`
This could easily be fixed by including 
`use APP\template\TemplateManager;`
in QuickSubmitPlugin.inc.php.
Then a new error occured:
`Uncaught Error: Class "APP\\submission\\SubmissionMetadataFormImplementation" not found in.../ojs/plugins/importexport/quickSubmit/QuickSubmitForm.inc.php:49`
The class seems not to exit any longer. Any Ideas how to fix this?

Yours,
Felix

**Comment by asmecher** [comment]
@felixhelix, what version of the QuickSubmit plugin do you have installed?

**Comment by felixhelix** [comment]
@asmecher Oh sorry, pulled an old version :| 
Updated, and now it works fine!
Cannot say why it didn`t work when I tried to install the plugin via the gallery.
