### ISSUE TITLE
QuickSubmit form requires abstract even if Section does not require abstracts (OJS v3.4.0.4 / QuickSubmit v1.0.7.1)

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/quickSubmit#77]
I have created a section and toggled the option that says abstracts are not required for that section. However, when I try to upload content to that section via QuickSubmit, I get the following error message:
```
**Errors occurred processing this form**
Please enter your article's abstract. (English) 
```
Presumably, QuickSubmit should take the requirements from the section settings. I don't recall this being a problem in 3.3 (recently did a massive backfile ingest via QuickSubmit in 3.3.0.14/15).

Currently running OJS v3.4.0.4 / QuickSubmit v1.0.7.1

**Comment by jankubanek** [comment]
Same issue here. OJS 3.4.0-5. Not even using QuickSubmit---a fresh OJS 3.4.0-5 install has the issue upon any submission.
Please fix.

**Comment by bozana** [comment]
This is solved here: https://github.com/pkp/pkp-lib/issues/2644 and should be available in the next plugin release.
Thus, closing this issue now...
