### ISSUE TITLE
Not working on OMP 3.3.0 - Unrecognized DAO SectionDAO!

### ISSUE THREAD

**Issue by marcbria** [pkp/quickSubmit#78]
**Description**
Plugin is correctly installed but when I click on "Import/Export Data" link I got the "Unrecognized DAO SectionDAO!" message.

**How to reproduce:**
1. Install plugin version [1.0.6-1](https://github.com/pkp/quickSubmit/releases/tag/v1_0_6-1) in OMP 3.3.0 via web interface (adding it manually in the plugins folder didn't work).
2. Plugin is recognized and automatically enabled.
3. Then I visit Installed Plugins and I click in "QuickSubmit > Import/Export Data" link.
A new page is open with a "Unrecognized DAO SectionDAO!" message.

Nothing relevant shown in server's logs.

**Details** 
Testest with pkpofficial/omp:3.3.0-15 image.

**Comment by bozana** [comment]
Hi @marcbria, should quickSubmit plugin work with OMP? Has it worked earlier?

**Comment by marcbria** [comment]
Hi Bozana,

I don't know.
Acording to PKP PS they are using it with some clients, but I'm not sure if is this version or a tunned one. :-(

Let me ask them.

**Comment by marcbria** [comment]
Sorry Bozana. I asked by I didn't get an answer.
Closing it because the problem is somehow fixed?

**Comment by bozana** [comment]
No, just because we do not have a version for OMP I know about...

**Comment by bozana** [comment]
Please reopen it if needed... I wanted to know what issues are open for the next plugin release that should happen soon...

**Comment by marcbria** [comment]
I will check again with next release. Thanks.

**Comment by pmangahis** [comment]
Sorry for the delay- our hosted clients that are using this plugin are on OMP 3.3.0.13

**Comment by bozana** [comment]
Hi @marcbria, it seems that plugin @pmangahis has mentioned is one from Antti-Jussi: https://github.com/ajnyga/quickSubmit/tree/omp...
