### ISSUE TITLE
OJS Version Compatibility

### ISSUE THREAD

**Issue by stephaniegalloOU** [pkp/quickSubmit#89]
README States quickSubmit is compatible with "OJS 3.5". Should this be OJS 3.4? 

Thanks!

**Comment by asmecher** [comment]
@stephaniegalloOU, use the Branch dropdown to choose a branch matching your OJS -- e.g. `main` (to be released as 3.5, what you're currently looking at), `stable-3_4_0` for 3.4.0-x, or `stable-3_3_0` for 3.3.0-x (LTS). Installing the plugin from the Plugin Gallery takes care of finding the right version for your OJS.
