### ISSUE TITLE
StageAssignmentDAO removal - port to new StageAssignment Eloquent schema

### ISSUE THREAD

**Issue by defstat** [pkp/quickSubmit#90]
This plugin is referencing StageAssignmentDAO. This reference and the related code needs to be adapted as part of the pkp/pkp-lib#9674 issue

---
**PRs**

quickSubmit: pkp/quickSubmit#91

**Comment by defstat** [comment]
@bozana do you have some time to review that?

**Comment by bozana** [comment]
Yes, I was traveling, but now I am back and will take a look...
